---
- hosts: local
  sudo: yes

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

  roles:
    # lock down server
    - { role: ubuntu-common,
        is_vagrant: true,
        sys: true,
        sys_hostname: server-docker.local
      }
    - { role: angstwad.docker_ubuntu, docker_group_members: [ 'vagrant' ] }
