---
- hosts: server
  sudo: true
  roles:
    - { role: deploy,
        app_tls: true,
        app_tls_cert: '{{playbook_dir}}/ssl/hello_world.pem',
        app_tls_key: '{{playbook_dir}}/ssl/hello_world.key'
      }
