---
- hosts: server
  sudo: yes
  roles:
    # lock down server
    - { role: ubuntu-common,
        is_vagrant: true,
        sys: true,
        sys_hostname: server,
        fail2ban: true,
        fail2ban_dest_email: "office@bcooling.com.au",
        sshd: true,
        sshd_max_auth_tries: 2,
        ufw: true,
        ufw_reject: {
          attacker: { port: 80, ip: 192.168.200.150 }
        }
      }
    # generate self-signed certificates
    - { role: ssl-cert,
        ssl_cert_name: "hello_world",
        ssl_cert_country: "AU",
        ssl_cert_locality: "Gold Coast",
        ssl_cert_organization: "bencooling",
        ssl_cert_state: "Queensland"
      }
    # http server
    - { role: nginx, nginx_conf: nginx.conf }
    # node application
    - { role: bencooling.node, version: 5.x }
