nodejs:
  image: node
  volumes:
    - $PWD/app:/var/www/app
  working_dir: /var/www/app
  ports:
    - 5000:5000
  command: node server.js
nginx:
  image: nginx
  volumes:
    - $PWD/nginx.conf:/etc/nginx/nginx.conf
    - $PWD/assets:/var/www/assets
  ports:
    - 5001:80
  links:
    - nodejs:nodejs
