# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = 'ubuntu/trusty64'
  config.vm.box_check_update = false
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512 # 2048 = 4GB
    vb.cpus = 1
  end

  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.network "private_network", ip: "192.168.200.200"
    config.vm.provider "virtualbox" do |vb|
      vb.name = "jenkins"
    end
    jenkins.vm.provision "ansible" do |ansible|
      ansible.limit = "jenkins"
      ansible.playbook = "ansible/jenkins.yml"
      ansible.sudo = true
    end
  end

  # config.vm.define "server" do |server|
  #   server.vm.hostname = "server"
  #   server.vm.network "private_network", ip: "192.168.200.100"
  #   config.vm.provider "virtualbox" do |vb|
  #     vb.name = "server"
  #   end
  #   server.vm.provision "ansible" do |ansible|
  #     ansible.limit = "server"
  #     ansible.playbook = "ansible/node.yml"
  #     ansible.sudo = true
  #   end
  # end

  # config.vm.define "attacker" do |attacker|
  #   attacker.vm.hostname = "attacker"
  #   attacker.vm.network "private_network", ip: "192.168.200.150"
  #   config.vm.provider "virtualbox" do |vb|
  #     vb.name = "attacker"
  #   end
  # end

end
